export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const CHANGE_MIN_PRICE = 'CHANGE_MIN_PRICE';
export const CHANGE_MAX_PRICE = 'CHANGE_MAX_PRICE';
export const CHANGE_TOUR_NAME = 'CHANGE_TOUR_NAME';

export const SET_TOURS = 'SET_TOURS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
